// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgzecuoyvpxkgdinxipj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnemVjdW95dnB4a2dkaW54aXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwOTQ3ODAsImV4cCI6MjA4NjY3MDc4MH0.huB7jZi9iACSprzKMHc5Z7qle6kk0wmOPy0cClLLBP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});